puts "Cleaning database..."

Perform.destroy_all
Spectacle.destroy_all

ActiveStorage::Blob.destroy_all
ActiveStorage::Attachment.destroy_all

puts "Create spectacles"

Spectacle.create!([
  {title: "Une Saison en Enfer", description: "Si seulement je pouvais expliquer le magnétisme qu’exerce ses textes... Rimbaud tu ne l’aimes pas, tu ne l’apprécies pas, tu ne le dégustes pas, tu ne le savoures pas, mais naturellement il t’envahit le monstre. Et surtout Une Saison en Enfer, tu ne la comprends pas... ça s’incruste. C’est un texte sans ossature réelle il est en perpétuel mouvement, il aime la religion puis il la foule aux pieds. Il tente de se comprendre. Alors voilà, c’est un combat, une bataille, un corps à corps, une empoignade. 7464 mots. Dans la bouche, 7464 mots telles des balles de fusil que je projette sur des pauvres innocents. Un paysage parsemé de pièges tels les mines dans les zones de combat. Et bien sûr la légende, le mythe, le mauvais garçon, le marginal. \"Allons, la marche, le fardeau, le désert, l’ennui et la colère\"... Jacques Livchine", company: "Théâtre de l'Unité"},
  {title: "Danse Machine Volume ", description: "Tu tapes le numéro de l’infoline et tombes sur une boîte vocale : tu rejoins la zone. C'est l'une des premières raves en Europe. Ici, pas besoin de costard ou de robe de soirée, plus de clivage entre les sociétés, tout le monde se retrouve pour faire la fête ! Que pourrait perturber cette insouciance ? Des basses rivales se rapprochent, le bruit d'un moteur, Milka, Ricky et leur caisse tunée s'invitent au bal. À Berlin, le Mur vient de tomber... Acid Tech vs. Eurodance, lasers et caissons, politique au point mort et virage sécuritaire : Danse Machine Volume est un spectacle pour la Fin de l'Histoire et après.", company: "Collectif La TOILE"},
  {title: "Murmures des Décasés", description: "Les \"décasés\", le \"décasage\" sont des termes communs à Mayotte qui nomment des rues et des quartiers, et qui paradoxalement, inspirent un quotidien angoissant hanté par ce mouvement permanent de déplacement. Le territoire de Mayotte regorge de multiples accents linguistiques, historiques et politiques. \"Murmures des décasés\" de Djodjo Kazadi, est un spectacle de danse théâtre où le corps déambule, se regroupe, se déplace, se perd dans l’évocation d’un passé étroitement lié aux croyances communautaires et animé par la transe d’un présent vertigineux. Les mots s’effacent progressivement pour laisser place à l’énergie et l’émotion dégagées par la subtilité chorégraphique des danseurs ; dans un univers scénographique happant, où les corps et les mots entremêlent le passé et le présent, le sacré et le politique.", company: "Cie Kazyadance - Djodjo Kazadi"},
  {title: "We love catastrophe ", description: "Un amour pour la panique et le sens du drame Un amour pour un concert qui tourne mal, Un amour pour un épais brouillard qui masque l'horizon Un amour pour une foule en délire Un amour pour un regard croisé et de deux corps qui se touchent Un amour pour une vague qui devient beaucoup trop grande Un amour pour une sirène qui hurle dans une forêt de béton Un amour, une brèche, une fièvre Un amour pour une jeunesse bruyante Un amour pour le rouge ou le rose Un amour pour un happy end We Love Catastrophe est une déclaration d'amour pour les espaces ouverts communs. Un moment de bascule festif, tragique, politique qui s'inscrit dans la mémoire collective des corps. Une foule de muscles, d'arêtes, de visages, d'individus qui s'entremêlent, dansent, s'élèvent et se figent. Le temps est mis à l'arrêt. Entre tension, réaction, confrontation et soulèvement, chacun depuis sa place est concerné.", company: "Collectif A/R"},
  {title: "La Concordance des temps ", description: "Le spectacle implique un duo de deux artistes, Pierre Jean Bréaud et Guillaume Sendron. Acrobates, ils ont poussé loin les prouesses techniques et ce n’est plus leur quête, pourtant leur goût pour le vertige reste entier et l’engagement physique est total. Leurs recherches se concentrent désormais sur des aspects plus subtils de leur pratique et les découvertes autour des notions du poids, de la relation et du déséquilibre ouvrent des champs tout aussi excitants à appréhender. Comme ils aiment à le rappeler : Quel sens a notre chemin d’acrobate de main à main, si ce n’est celui du toucher, de toucher et d’être touché. Dans un dispositif en bi-frontal, où nous serons au plus près des artistes, une rencontre sensible, vertigineuse, dans la délicatesse de la complicité où la notion même de \"porter\" est considérée comme un acte fondateur de notre humanité.", company: "Le doux supplice"},
  {title: "RoZéO ", description: "Juchées sur de frêles tiges de métal, portées par un souffle imperceptible, elles oscillent doucement. Elles remuent le ciel et dansent dans l’air agité. À la manière des roseaux de Camargue, elles dialoguent avec le paysage. Elles évoquent des images de bergères, sorcières, prêtresses ou amazones. Elles nous invitent à regarder au lointain et sentir le souffle de l’air. Sons soufflés, chuchotés, murmurés, sifflés, une musicienne live accompagne l'installation. Entre musique électronique pré-enregistrée et field recording, la partition se double d'un travail live autour de la voix et d'instruments multiples. Suspension, immobilité, oscillations lentes invitent à la contemplation, à porter un regard \"du plan large”. RoZéO est une installation vivante à observer lentement, une respiration profonde avec le ciel pour horizon.", company: "Association Gratte Ciel"},
  {title: "Madame, Monsieur, Bonsoir ! ", description: "Depuis 20 ans, chaque année, le baromètre de crédibilité des médias indique que 50% des français ne font pas confiance aux médias...Et pourtant, tout le monde continue d'écouter, de s'informer pour se sentir appartenir au monde. Sans s'insurger. En pensant simplement à développer son esprit critique pour déjouer les pièges lancés par les médias de masse. Mais...et si il n'y avait pas de pièges à débusquer? Et puis Que faisons-nous de toutes ces informations que nous ingurgitons au quotidien ? Dans la lignée de notre précédente création « Argent, pudeurs et décadences », nous proposons ici une comédie exutoire sur la fabrication et la consommation de l'information, en poussant les situations réelles dans leurs retranchements, menant au poétique et à l'absurde. Un spectacle sur l'opinion publique, la liberté d'expression, notre rapport à la démocratie et à la violence banalisée.", company: "AIAA - Atelier d'Initiatives Artistiques et Artisanales"},
  {title: "Ourse ", description: "« Un jour, j’ai fait l’amer constat que je n’arrivais plus à voir la beauté. Des raisons, il y en a toutes sortes : le monde anxiogène, la solitude des gens dans des sociétés ultra connectées, la rupture avec notre instinct animal, exister à tout prix et laisser des traces…» La beauté se ferait-elle de plus en plus discrète ? Pourtant, ne nous permet-elle pas de retrouver une certaine place dans l’univers ? Ourse est une quête pour partir à la recherche de la beauté. Nous tenterons de la dénicher, sous forme une joyeuse allégorie qui nous invitera à aimer ce que nous ne comprenons pas.", company: "Bélé Bélé"}
])

puts "Create performs"

Perform.create!([
  {address: "4 Place Du Port Villiers, 71100 Chalon-sur-Saône, France", latitude: 46.7801408, longitude: 4.8549736, title: nil, collected: true, spectacle_id: 1, start: "2023-07-21 11:00:00"},
  {address: "4 Place Du Port Villiers, 71100 Chalon-sur-Saône, France", latitude: 46.7801408, longitude: 4.8549736, title: nil, collected: true, spectacle_id: 1, start: "2023-07-21 16:00:00"},
  {address: "4 Place Du Port Villiers, 71100 Chalon-sur-Saône, France", latitude: 46.7801408, longitude: 4.8549736, title: nil, collected: true, spectacle_id: 1, start: "2023-07-22 11:00:00"},
  {address: "4 Place Du Port Villiers, 71100 Chalon-sur-Saône, France", latitude: 46.7801408, longitude: 4.8549736, title: nil, collected: false, spectacle_id: 1, start: "2023-07-22 16:00:00"},
  {address: "Place Saint-Vincent, 71100 Chalon-sur-Saône, France", latitude: 46.7819522, longitude: 4.8582605, title: nil, collected: false, spectacle_id: 2, start: "2023-07-21 22:00:00"},
  {address: "Place Saint-Vincent, 71100 Chalon-sur-Saône, France", latitude: 46.7819522, longitude: 4.8582605, title: nil, collected: false, spectacle_id: 2, start: "2023-07-22 22:00:00"},
  {address: "Impasse De L'ancienne Prison, 71100 Chalon-sur-Saône, France", latitude: 46.7807163, longitude: 4.8557585, title: nil, collected: false, spectacle_id: 3, start: "2023-07-22 14:30:00"},
  {address: "Impasse De L'ancienne Prison, 71100 Chalon-sur-Saône, France", latitude: 46.7807163, longitude: 4.8557585, title: nil, collected: false, spectacle_id: 3, start: "2023-07-23 14:30:00"},
  {address: "Place De L'hôtel De Ville, 71100 Chalon-sur-Saône, France", latitude: 46.7809003, longitude: 4.853015, title: nil, collected: false, spectacle_id: 7, start: "2023-07-21 16:30:00"},
  {address: "Place De L'hôtel De Ville, 71100 Chalon-sur-Saône, France", latitude: 46.7809003, longitude: 4.853015, title: nil, collected: false, spectacle_id: 7, start: "2023-07-22 16:30:00"},
  {address: "Place De L'hôtel De Ville, 71100 Chalon-sur-Saône, France", latitude: 46.7809003, longitude: 4.853015, title: nil, collected: true, spectacle_id: 7, start: "2023-07-22 17:00:00"},
  {address: "Rue Aux Fèvres, 71100 Chalon-sur-Saône, France", latitude: 46.7831702, longitude: 4.8571934, title: nil, collected: false, spectacle_id: 8, start: "2023-07-20 10:00:00"},
  {address: "Rue Aux Fèvres, 71100 Chalon-sur-Saône, France", latitude: 46.7831702, longitude: 4.8571934, title: nil, collected: false, spectacle_id: 8, start: "2023-07-21 10:00:00"},
  {address: "Rue Aux Fèvres, 71100 Chalon-sur-Saône, France", latitude: 46.7831702, longitude: 4.8571934, title: nil, collected: false, spectacle_id: 8, start: "2023-07-22 10:00:00"}
])

puts "Cloudinary stuffs"

ActiveStorage::Blob.create!([
  {key: "n62heqsx9gnajsnz0t0gthfn15h2", filename: "img-03f1cbb2dcd54c1139294f46d0b91329.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, service_name: "cloudinary", byte_size: 281779, checksum: "Ix6rn/9xVlzfpZRl783qKQ=="},
  {key: "gykd1531px8h4h5bz7m945irmjwp", filename: "img-85273c9da600f6e6606f52ed57eb084b.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, service_name: "cloudinary", byte_size: 218159, checksum: "ybvB4Ga5zwgi12Nw8ny7Tg=="},
  {key: "0ubey9972no0nl1ypsa1943lsscb", filename: "img-6c5a0aec5a27df5b85354c10c33e805e.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, service_name: "cloudinary", byte_size: 327966, checksum: "JWyuDhVXmonwehqIM617rg=="},
  {key: "fg3oyjfze0xd842vejeadk3qvbbe", filename: "img-acad18b33fed7fa2c038982244c36daa.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, service_name: "cloudinary", byte_size: 279973, checksum: "xXNnowz+WwTWuHSHwUowqQ=="},
  {key: "xl06mqzojopg1oviuyvbv78qxw87", filename: "img-825a7421e6af2337b3086748dcc7c92c.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, service_name: "cloudinary", byte_size: 81920, checksum: "vY0SWjkxqBQrWEpu9hdckw=="},
  {key: "f2bfpkbzp3d0rd7smek9l3inzcxg", filename: "img-41a6522de3a2106352446b4077a55bec.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, service_name: "cloudinary", byte_size: 148795, checksum: "t3IVgq++axUk24lu2Ng4NA=="},
  {key: "xj3qm202eb0dn1mhvhxfte0wdw7d", filename: "img-18b60d06170d8c33ab8b73bd13a30b17.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, service_name: "cloudinary", byte_size: 158060, checksum: "9LrwuE9i6NAGmIx9kPfOBw=="},
  {key: "fyqbldt793q8jbklaszgcj0tud8m", filename: "img-bfa2294f694896039966dd96ca720df1.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, service_name: "cloudinary", byte_size: 406258, checksum: "noApsx6Qnvn4GPPwOrh+RA=="}
])
ActiveStorage::Attachment.create!([
  {name: "photos", record_type: "Spectacle", record_id: 1, blob_id: 1},
  {name: "photos", record_type: "Spectacle", record_id: 2, blob_id: 2},
  {name: "photos", record_type: "Spectacle", record_id: 3, blob_id: 3},
  {name: "photos", record_type: "Spectacle", record_id: 4, blob_id: 4},
  {name: "photos", record_type: "Spectacle", record_id: 5, blob_id: 5},
  {name: "photos", record_type: "Spectacle", record_id: 6, blob_id: 6},
  {name: "photos", record_type: "Spectacle", record_id: 7, blob_id: 7},
  {name: "photos", record_type: "Spectacle", record_id: 8, blob_id: 8}
])
